### PR TITLE
support of @Reference(value = Any.class)

### PR DESCRIPTION
**Pull request by rmannibucau**

### CODE REVIEW

**Review by jbonofre — APPROVED** [review]
LGTM, thanks.

**Review by rotty3000 — APPROVED** [review]
LGTM

**Comment by rotty3000** [comment]
Once the upstream asf build completes there will be a snapshot available.

**Comment by rotty3000** [comment]
https://builds.apache.org/view/A/view/Aries2/job/Aries-cdi-master/

**Pull request merged**
